### ISSUE TITLE
Figure out how to update pre-commit config 

### ISSUE THREAD

**Issue by phinate** [alan-turing-institute/python-project-template#18]
Would be nice to figure out how to automatically update the `.pre-commit-config.yaml` file.

This could be done with [pre-commit.ci](https://pre-commit.ci), which is set up on this repo, but can't find the file since it's not in the root of the directory! Haven't yet found a way to configure this.

**Comment by Jacob-Stevens-Haas** [comment]
Hey Nathan, how about making the template repository a git submodule hosted in a different repo?  That way, pre-commit-config.yml would be at the top of the submodule's repo?

A potential, more "manual" version might be  a cron-based github action to install from pre-commit-config.yml, run `pre-commit autoupdate`, and PR any differences.

**Comment by jack89roberts** [comment]
We have a cron job updating poetry + pre-commit dependency versions once a month [in the ARC template](https://github.com/alan-turing-institute/ARC-project-template/blob/main/.github/workflows/update_template.yml). For the directory issue, is it not possible to cd into the sub-directory and then run the update from there?

**Comment by phinate** [comment]
This was added as part of #27, though I haven't seen the commit yet (possibly due to it only being monthly like yours @jack89roberts). Maybe I should merge it as a triggerable workflow first and make sure it runs?

**Comment by jack89roberts** [comment]
It should run on Friday the way it's configured now so not too long to wait otherwise 😄

**Comment by Jacob-Stevens-Haas** [comment]
> Maybe I should merge it as a triggerable workflow first and make sure it runs?

I've gotten CI wrong more than right, so I did this when I PR'd a cron-based workflow. Once it worked, I set the cron job to run shortly after I expect to merge the change, in order to get feedback if I made some additional mistake.

**Comment by phinate** [comment]
This is fixed now by #45 and co!
