### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by phinate** [alan-turing-institute/python-project-template#2]
Need to iron out what would go here -- it may be that this varies substantially between projects.

**Comment by radka-j** [comment]
Me and Camila plan to adapt the Turing Data Stories CoC for this repo: https://github.com/KatrionaGoldmann/TuringDataStories/tree/ethos_KG

We like that it is quite minimal and yet comprehensive.

The plan is for the CoC to only include the "our standards" section. The remaining sections ("our responsibilities" and "enforcement") will be commented out. This means that anyone using this repo template isn't by default signing up to manage a community around their project. Nevertheless, we like for the template to include the option for doing so.

**Comment by phinate** [comment]
As discussed offline: we're going to tackle this by providing a minimal CoC (that we'd like users to read and extend), or provide the file blank if people want to write their own. We'll also discourage using _no_ CoC, as even small projects can benefit + it's a good learning opportunity for the maintainers!
