### ISSUE TITLE
Invalid version raised by copier

### ISSUE THREAD

**Issue by eddableheath** [alan-turing-institute/python-project-template#25]
When trying to use copier to set up the template the following error is thrown:

`packaging.version.InvalidVersion: Invalid version: 'v2024-02-06.post1+g42a0b88'`

which occurs after the set up is complete.

This occurs with versions of copier back to `8.0.0`, before which it doesn't run at all.

**Comment by phinate** [comment]
Finally got around to look into this — I had a GitHub tag on this repo that was formatted as above (`v2024-02-06`), which wasn't compatible with [PEP 440 versioning](https://peps.python.org/pep-0440/). Should work now!

**Comment by boykovdn** [comment]
I tried it today and it works, thanks!
